# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd025e9646fd408d176395213c77fef822d200b817d4adb3b703139ec5896fe4c8092a8e903d3a7663fc6c341cb5f37d7c0aa93e0b6528b88014c664e0ed45f9

test:
  secret_key_base: 01030a15a6adabc2322c355a655b479f4a5189979a2035549d58dbf8e662b27cd8b85ac2165148ac2f19b4bd66f1619a33abdac1637e344af88eb55c2f67c550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
